# Generated by Django 4.2 on 2023-05-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tanks", "Танки"),
                            ("heals", "Хилы"),
                            ("dnd", "ДНД"),
                            ("merchants", "Торговцы"),
                            ("guildmasters", "Гилдамастеры"),
                            ("giver_quest", "Квестгиверы"),
                            ("blackmiths", "Кузнецы"),
                            ("leatherworkers", "Кожевники"),
                            ("potions_masters", "Зельевары"),
                            ("spellmasters", "Мастера заклинаний"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок объявления"
                    ),
                ),
                (
                    "text",
                    tinymce.models.HTMLField(
                        max_length=4000, verbose_name="Текст объявления"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Время создания объявления"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор объявления",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
