# Generated by Django 4.2 on 2023-05-04 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advert", "0002_alter_advert_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="Принят")),
                ("text", models.CharField(max_length=255, verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Время создания"),
                ),
                (
                    "advert",
                    models.ForeignKey(
                        help_text="Объявление",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advert.advert",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
    ]
