# Generated by Django 4.2 on 2023-05-04 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advert", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
        migrations.AlterField(
            model_name="advert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания объявления"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="advert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advert.advert",
                verbose_name="Объявление",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=1000, verbose_name="Текст"),
        ),
    ]
